name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  
jobs:
  xcode_test:
    name: Test on destination ${{ matrix.destination }}
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["platform=macOS", "platform=iOS Simulator,name=iPhone 8", "platform=tvOS Simulator,name=Apple TV"]
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2'
      - uses: actions/checkout@v1
      - name: update submodules
        run: git submodule update --init
      - name: xcodebuild test ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild test -scheme Meter -destination "${{ matrix.destination }}" | xcpretty
  carthage_build:
    name: Build with Carthage
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2'
      - uses: actions/checkout@v1
      - name: update submodules
        run: git submodule update --init
      - name: carthage build
        run: carthage build --no-skip-current --use-xcframeworks
  swift_test:
    name: Test with Swift
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2'
      - uses: actions/checkout@v1
      - name: swift test
        run: swift test