name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - '.editorconfig'
      - '.spi.yml'
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer

jobs:
  test-13:
    name: Test macOS 13
    runs-on: macOS-13
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          # the test copies files, and that fails to built for other platforms for some reason...
          # - "platform=iOS Simulator,name=iPhone 12"
          # - "platform=watchOS Simulator,name=Apple Watch Series 6 (40mm)"

    steps:
      - uses: actions/checkout@v4
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme Meter -destination "${{ matrix.destination }}" test | xcbeautify

  test-14:
    name: Test macOS 14
    runs-on: macOS-14
    strategy:
      matrix:
        destination:
          - "platform=macOS"

    steps:
      - uses: actions/checkout@v4
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme Meter -destination "${{ matrix.destination }}" test | xcbeautify
